[2025-07-15T00:12:14.385+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_to_snowflake.processing_tables manual__2025-07-15T00:12:12.245493+00:00 map_index=2 [queued]>
[2025-07-15T00:12:14.399+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_to_snowflake.processing_tables manual__2025-07-15T00:12:12.245493+00:00 map_index=2 [queued]>
[2025-07-15T00:12:14.400+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-15T00:12:14.417+0000] {taskinstance.py:2191} INFO - Executing <Mapped(_PythonDecoratedOperator): processing_tables> on 2025-07-15 00:12:12.245493+00:00
[2025-07-15T00:12:14.421+0000] {standard_task_runner.py:60} INFO - Started process 159 to run task
[2025-07-15T00:12:14.426+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_to_snowflake', 'processing_tables', 'manual__2025-07-15T00:12:12.245493+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/etl_transfer_to_stage.py', '--cfg-path', '/tmp/tmpb12rc65h', '--map-index', '2']
[2025-07-15T00:12:14.431+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask processing_tables
[2025-07-15T00:12:14.490+0000] {task_command.py:423} INFO - Running <TaskInstance: data_extraction_to_snowflake.processing_tables manual__2025-07-15T00:12:12.245493+00:00 map_index=2 [running]> on host ba480c39b9ec
[2025-07-15T00:12:14.560+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_extraction_to_snowflake' AIRFLOW_CTX_TASK_ID='processing_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:12:12.245493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T00:12:12.245493+00:00'
[2025-07-15T00:12:14.566+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2025-07-15T00:12:14.580+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2025-07-15T00:12:14.609+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2025-07-15T00:12:14.620+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_transfer_to_stage.py", line 103, in processing_each_table
    cursor.execute(insert_query,row)
psycopg2.errors.UndefinedTable: relation "dw_hr_nives.shift_type_info" does not exist
LINE 1: INSERT INTO DW_HR_NIVES.shift_type_info (id, shift_type_id, ...
                    ^

[2025-07-15T00:12:14.628+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_extraction_to_snowflake, task_id=processing_tables, map_index=2, execution_date=20250715T001212, start_date=20250715T001214, end_date=20250715T001214
[2025-07-15T00:12:14.636+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 132 for task processing_tables (relation "dw_hr_nives.shift_type_info" does not exist
LINE 1: INSERT INTO DW_HR_NIVES.shift_type_info (id, shift_type_id, ...
                    ^
; 159)
[2025-07-15T00:12:14.645+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-15T00:12:14.661+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
